name: group_project2
description: A Flutter Sign Translate project

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  video_player: ^2.8.2

flutter:
  uses-material-design: true
  assets:
    - AI/DataBase/DOWNLOADS/
    - AI/DataBase/videos.json
